INSERT INTO tb_user(email) VALUES ('maria@gmail.com');

INSERT INTO tb_movie(score, count, title, image) VALUES (5.0, 1, 'Vikings: Valhalla', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/izIMqapegdEZj0YVDyFATPR8adh.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0,'Eternos', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/mzezdUZEnpiUIlxpdyLO1R08Lqm.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0,'Sonic: O Filme', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/eOC0FSGqyzcnnx7XFgLazI9nACT.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0,'Hotel Transilvânia: Transformonstrão', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/9PbtCo5IIkd26WPQfZUpPyn6fTz.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0,'Meu Tio', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/sDPNwSe63WACVlHap7un6AgbqgO.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Paixões Ardentes', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/lWlsZIsrGVWHtBeoOeLxIKDd9uy.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Um Dia Difícil ', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/bktIW44oeurTptHLdkj7ayc4zbH.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Batman', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/wd7b4Nv9QBHDTIjc2m7sr0IUMoh.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Vikings: Valhalla', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/izIMqapegdEZj0YVDyFATPR8adh.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0,'Eternos', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/mzezdUZEnpiUIlxpdyLO1R08Lqm.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0,'Sonic: O Filme', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/eOC0FSGqyzcnnx7XFgLazI9nACT.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0,'Hotel Transilvânia: Transformonstrão', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/9PbtCo5IIkd26WPQfZUpPyn6fTz.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0,'Meu Tio', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/sDPNwSe63WACVlHap7un6AgbqgO.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Paixões Ardentes', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/lWlsZIsrGVWHtBeoOeLxIKDd9uy.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Um Dia Difícil ', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/bktIW44oeurTptHLdkj7ayc4zbH.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Batman', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/wd7b4Nv9QBHDTIjc2m7sr0IUMoh.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Vikings: Valhalla', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/izIMqapegdEZj0YVDyFATPR8adh.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0,'Eternos', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/mzezdUZEnpiUIlxpdyLO1R08Lqm.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0,'Sonic: O Filme', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/eOC0FSGqyzcnnx7XFgLazI9nACT.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0,'Hotel Transilvânia: Transformonstrão', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/9PbtCo5IIkd26WPQfZUpPyn6fTz.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0,'Meu Tio', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/sDPNwSe63WACVlHap7un6AgbqgO.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Paixões Ardentes', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/lWlsZIsrGVWHtBeoOeLxIKDd9uy.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Um Dia Difícil ', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/bktIW44oeurTptHLdkj7ayc4zbH.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Batman', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/wd7b4Nv9QBHDTIjc2m7sr0IUMoh.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Vikings: Valhalla', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/izIMqapegdEZj0YVDyFATPR8adh.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0,'Eternos', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/mzezdUZEnpiUIlxpdyLO1R08Lqm.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0,'Sonic: O Filme', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/eOC0FSGqyzcnnx7XFgLazI9nACT.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0,'Hotel Transilvânia: Transformonstrão', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/9PbtCo5IIkd26WPQfZUpPyn6fTz.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0,'Meu Tio', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/sDPNwSe63WACVlHap7un6AgbqgO.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Paixões Ardentes', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/lWlsZIsrGVWHtBeoOeLxIKDd9uy.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Um Dia Difícil ', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/bktIW44oeurTptHLdkj7ayc4zbH.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Batman', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/wd7b4Nv9QBHDTIjc2m7sr0IUMoh.jpg');

INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 1, 5.0);